# Generated by Django 2.1.7 on 2019-05-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ela',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ManyToManyField(to='UI.Barcode')),
            ],
        ),
    ]
