# Generated by Django 2.1.7 on 2019-05-01 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0002_ela'),
    ]

    operations = [
        migrations.CreateModel(
            name='fuge',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('barcode', models.ManyToManyField(to='UI.Barcode')),
            ],
        ),
    ]
