# Generated by Django 2.1.7 on 2019-05-01 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0003_fuge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ela',
            name='item',
        ),
        migrations.AddField(
            model_name='ela',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='UI.Barcode'),
        ),
    ]
