# Generated by Django 2.1.7 on 2019-05-01 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0004_auto_20190501_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuge',
            name='barcode',
        ),
        migrations.AddField(
            model_name='fuge',
            name='barcode',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='UI.Barcode'),
        ),
    ]
