# Generated by Django 2.1.7 on 2019-05-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0005_auto_20190501_2034'),
    ]

    operations = [
    ]
