# Generated by Django 2.1.7 on 2019-05-24 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UI', '0006_auto_20190524_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFridgeList',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('barcode', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='UI.Barcode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProductList',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='UI.Barcode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
