# Generated by Django 2.1.7 on 2019-05-24 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0007_auto_20190524_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfridgelist',
            name='barcode',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UI.Barcode'),
        ),
        migrations.AlterField(
            model_name='userproductlist',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UI.Barcode'),
        ),
    ]
