# Generated by Django 2.1.7 on 2019-05-24 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0009_auto_20190524_1939'),
    ]

    operations = [
    ]
