# Generated by Django 2.1.7 on 2019-05-24 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UI', '0010_auto_20190524_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfridgelist',
            name='user',
        ),
        migrations.AddField(
            model_name='userfridgelist',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='userproductlist',
            name='user',
        ),
        migrations.AddField(
            model_name='userproductlist',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
