# Generated by Django 2.1.7 on 2019-05-28 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0016_auto_20190526_1915'),
    ]

    operations = [
    ]
