# Generated by Django 2.1.7 on 2019-05-28 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0017_auto_20190528_1920'),
    ]

    operations = [
    ]
