# Generated by Django 2.1.7 on 2019-05-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0018_auto_20190528_1938'),
    ]

    operations = [
    ]
