# Generated by Django 2.1.7 on 2019-05-31 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UI', '0019_auto_20190528_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoOrder',
            fields=[
                ('auto_order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(default='not_init', max_length=20)),
                ('scheduled_date', models.DateTimeField(null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AutoOrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UI.AutoOrder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='UI.Barcode')),
            ],
        ),
    ]
