# Generated by Django 2.1.7 on 2019-06-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0021_auto_20190601_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoorder',
            name='scheduled_time',
            field=models.TextField(null=True),
        ),
    ]
