# Generated by Django 2.1.7 on 2019-06-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0023_auto_20190602_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoorder',
            name='date_sent',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='date_sent',
            field=models.DateTimeField(null=True),
        ),
    ]
